// <auto-generated />
namespace TH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_table_Nhanvien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_table_Nhanvien));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060551597_Create_table_Nhanvien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
